blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from bloges import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bloges.urls', namespace='bloges')),
    # path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloges/urls.py
from django.urls import path
from . import views

app_name = 'bloges'


urlpatterns = [
    path('', views.IndexView, name="index"),
    path('blog/', views.post_list, name='post_list'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('category/<slug:slug>/', views.category_list, name='category_list'),
    # path('category/<int:pk>/', views.category_detail, name='category_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    # path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('<slug:category_slug>', views.IndexView, name='cat_img_by_category'),
    # path('<int:id>/', views.cat_img_detail, name='cat_img_detail'),
    # path('blog/bloges/', views.BlogView.as_view(), name='blogeses'),
    # path('blog/singleblog/', views.BlogSingleView.as_view(), name='singleblog'),
]

bloges/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField




class ChangeHeader(models.Model):
	header_name = models.CharField(max_length=15, verbose_name='Название модели')
	header_single_letter = models.CharField(max_length=1, verbose_name='Заглавная буква лого')
	header_logo_text = models.CharField(max_length=20, verbose_name='Текст букв лого')
	header_main = models.CharField(max_length=250, verbose_name='Название меню')
	header_features = models.CharField(max_length=250, verbose_name='Название 2 блока')
	header_work = models.CharField(max_length=250, verbose_name='Название 3 блока')
	header_service = models.CharField(max_length=250, verbose_name='Название 4 блока')
	header_blog = models.CharField(max_length=250, verbose_name='Название 5 блока')
	header_price = models.CharField(max_length=250, verbose_name='Название 6 блока')
	header_about = models.CharField(max_length=250, verbose_name='Название 7 блока')
	header_contact = models.CharField(max_length=250, verbose_name='Название 7 блока')
	header_phone = PhoneNumberField(null=False, blank=False, unique=True)

	def __str__(self):
		return self.header_name

	class Meta:
		verbose_name = 'Header'
		verbose_name_plural = verbose_name


class ChangeFooter(models.Model):
	footer_logo_img = models.ImageField(upload_to='footerimg/')
	footer_title = models.TextField()
	footer_facebook = models.CharField(max_length=250, verbose_name='Ссылка на фейсбук')
	footer_twitter = models.CharField(max_length=250, verbose_name='Ссылка на твиттер')
	footer_in = models.CharField(max_length=250, verbose_name='Ссылка на in')
	footer_telegram = models.CharField(max_length=250, verbose_name='Ссылка на telegram')
	footer_vimeo = models.CharField(max_length=250, verbose_name='Ссылка на vimeo')
	footer_pictures = models.CharField(max_length=250, verbose_name='Ссылка на pictures')
	footer_left_title = models.CharField(max_length=250, verbose_name='Заголовок (слева) контакт')
	footer_left_map = models.CharField(max_length=250, verbose_name='Контакт Адрес')
	footer_left_email = models.CharField(max_length=250, verbose_name='Контакт почты')
	footer_center_title = models.CharField(max_length=250, verbose_name='Заголовок center')
	footer_center_desc = models.CharField(max_length=250, verbose_name='Описание работы')
	footer_center_work = models.CharField(max_length=250, verbose_name='MON - FRI : 9.00 AM TO 5.00 PM')
	footer_center_work1 = models.CharField(max_length=250, verbose_name='SAT - SUN : 11.00 AM TO 3.00 PM')

	def __str__(self):
		return self.footer_title

	class Meta:
		verbose_name = 'Footer'
		verbose_name_plural = verbose_name


class ChangeFooterTitleGallery(models.Model):
	footer_right_title = models.CharField(max_length=250, verbose_name='Заголовок справа')

	def __str__(self):
		return self.footer_right_title

	class Meta:
		verbose_name = 'Заголовок справа'
		verbose_name_plural = verbose_name


class ChangeFooterGallery(models.Model):
	footer_right_name = models.CharField(max_length=250, verbose_name='Название картинки', default='this stroke')
	footer_right_img = models.ImageField(upload_to='footerimg/')

	def __str__(self):
		return self.footer_right_name

	class Meta:
		verbose_name = 'Картинка'
		verbose_name_plural = 'Картинки'

pagebanner/models.py
from django.db import models


class PageBanner(models.Model):
	banner_name = models.CharField(max_length=250, verbose_name='Название главного заголовка')
	banner_btn_1 = models.CharField(max_length=250, verbose_name='Название первого раздела')
	banner_btn_2 = models.CharField(max_length=250, verbose_name='Название второго раздела')
	banner_btn_3 = models.CharField(max_length=250, verbose_name='Название третьего раздела')

	def __str__(self):
		return self.banner_name

	class Meta:
		verbose_name = 'Заголовок баннера'
		verbose_name_plural = verbose_name

bloges/forms.py
from django import forms
from fmblog.models import Comment

class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')

bloges/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView
from slider.models import Slider
from features.models import Features
from gallery.models import Category, Photo
from django.urls import reverse
from offer.models import ReloadTitle, ReloadTitleDesc
from buildws.models import BuildWebsite, BuildButton, MainImage
from fmblog.models import FmBlog, Comment, PublishedManager, ChangeTitle, ChangeTitleCategory, CategoryList
from price.models import PriceChangedTitle, PriceChanged
from team.models import TeamMainTitle, TeamBox
from bloges.models import ChangeHeader, ChangeFooter, ChangeFooterTitleGallery, ChangeFooterGallery
from pagebanner.models import PageBanner
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag

def IndexView(request):
	#Хеадер
	header_phone = ChangeHeader.objects.get(pk=1)

	#Слайдер
	slider_list = Slider.objects.all()

	#Замена функций
	features_all = Features.objects.all()
	features_1 = Features.objects.get(pk=1)
	features_2 = Features.objects.get(pk=2)
	features_3 = Features.objects.get(pk=3)
	features_4 = Features.objects.get(pk=4)
	features_5 = Features.objects.get(pk=5)
	features_6 = Features.objects.get(pk=6)

	#Категории для галлереи
	category = None
	categories = Category.objects.all()
	category_car = Category.objects.in_bulk(['car'], field_name='slug')
	photo_car = Photo.objects.filter(category__name='car')
	photo_girl = Photo.objects.filter(category__name='girls')
	photo_mushrooms = Photo.objects.filter(category__name='mushroms')
	photo_people = Photo.objects.filter(category__name='people')

	#Что мы предлагаем
	off_re_title = ReloadTitle.objects.get(pk=1)

	#Карточки
	rtd_1_title = ReloadTitleDesc.objects.get(pk=1)
	rtd_2_title = ReloadTitleDesc.objects.get(pk=2)
	rtd_3_title = ReloadTitleDesc.objects.get(pk=3)

	#Buildws
	build_txt = BuildWebsite.objects.get(pk=1)
	build_btn = BuildButton.objects.all()
	build_img = MainImage.objects.get(pk=1)

	#Blog
	ch_title = ChangeTitle.objects.get(pk=1)

	posts = FmBlog.published.all()

	#Price and plans
	price_main_title = PriceChangedTitle.objects.get(pk=1)
	price_title = PriceChanged.objects.get(pk=1)
	price_title_2 = PriceChanged.objects.get(pk=2)
	price_title_3 = PriceChanged.objects.get(pk=3)

	#Team
	team_title = TeamMainTitle.objects.get(pk=1)
	team_info_1 = TeamBox.objects.get(pk=1)
	team_info_2 = TeamBox.objects.get(pk=2)
	team_info_3 = TeamBox.objects.get(pk=3)
	team_info_4 = TeamBox.objects.get(pk=4)
	team_info_5 = TeamBox.objects.get(pk=5)
	team_info_6 = TeamBox.objects.get(pk=6)
	team_info_7 = TeamBox.objects.get(pk=7)
	team_info_8 = TeamBox.objects.get(pk=8)

	#Footer
	footer_content = ChangeFooter.objects.get(pk=1)


	#Flicker Gallery
	#title
	flick_name = ChangeFooterTitleGallery.objects.get(pk=1)
	
	#image
	flick_img = ChangeFooterGallery.objects.all()
	
	dic_obj = {'header_phone' : header_phone,
			   'slider_list':slider_list,
			   'features_all' : features_all,
			   'features_1' : features_1,
			   'features_2' : features_2, 'features_3' : features_3,
			   'features_4' : features_4, 'features_5' : features_5, 'features_6' : features_6,
			   'categories' : categories,
			   'category_car' : category_car,
			   'photo_car' : photo_car, 'photo_girl' : photo_girl, 'photo_mushrooms' : photo_mushrooms, 'photo_people' : photo_people,
			   'off_re_title' : off_re_title,
			   'rtd_1_title' : rtd_1_title, 'rtd_2_title' : rtd_2_title, 'rtd_3_title' : rtd_3_title,
			   'build_btn' : build_btn, 'build_txt' : build_txt, 'build_img' : build_img,
			   'ch_title' : ch_title, 'posts' : posts,
			   'price_main_title' : price_main_title,
			   'price_title' : price_title, 'price_title_2' : price_title_2, 'price_title_3' : price_title_3,
			   'team_title' : team_title,
			   'team_info_1' : team_info_1, 'team_info_2' : team_info_2, 'team_info_3' : team_info_3, 'team_info_4' : team_info_4,
			   'team_info_5' : team_info_5, 'team_info_6' : team_info_6, 'team_info_7' : team_info_7, 'team_info_8' : team_info_8,
			   'footer_content' : footer_content, 'flick_name' : flick_name, 'flick_img' : flick_img}

	return render(request, 'indexex.html', dic_obj)


def post_list(request, tag_slug=None):
	#Хеадер
	header_phone = ChangeHeader.objects.get(pk=1)


	object_list = FmBlog.published.all()

	# #ТЭГИ
	# tag = None

	# if tag_slug:
	# 	tag = get_object_or_404(Tag, slug=tag_slug)
	# 	object_list = object_list.filter(tags__in=[tag])


	#ПАГИНАЦИЯ
	paginator = Paginator(object_list, 3)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	#Посты
	obj_post = FmBlog.published.filter().order_by('-publish')[:4]

	#Заголовок категорий
	category_title = ChangeTitleCategory.objects.get(pk=1)

	category_name = CategoryList.objects.all()

	#titlebanner
	banner_title = PageBanner.objects.get(pk=1)

	#Footer
	footer_content = ChangeFooter.objects.get(pk=1)

	#Flicker Gallery
	#title
	flick_name = ChangeFooterTitleGallery.objects.get(pk=1)
	
	#image
	flick_img = ChangeFooterGallery.objects.all()

	dict_obj = {'header_phone' : header_phone,
				'page' : page,
				'posts' : posts,
				'category_title' : category_title, 'category_name' : category_name,
				'banner_title' : banner_title,
				'footer_content' : footer_content,
				'flick_name' : flick_name,
				'flick_img' : flick_img,
				'obj_post' : obj_post,
				# 'tag' : tag,
				'object_list' : object_list}

	return render(request, 'blog/main_direct.html', dict_obj)

# def post_list_by_tag(request, tag_slug=None):

# 	#ТЭГИ
# 	tag = None

# 	if tag_slug:
# 		tag = get_object_or_404(Tag, slug=tag_slug)
# 		object_list = object_list.filter(tags__in=[tag])

# 	dict_obj = {'tag' : tag}

# 	return render(request, 'blog/main_direct.html', dict_obj)


def category_list(request, slug):
	
	#Хеадер
	header_phone = ChangeHeader.objects.get(pk=1)
	
	#Заголовок категорий
	category_title = ChangeTitleCategory.objects.get(pk=1)
	category_one = CategoryList.objects.filter(slug='for-girl')

	category_two = CategoryList.objects.get(slug=slug)
	post = FmBlog.objects.filter(category=category_two)
	last_postest = FmBlog.objects.filter(category=category_two)[:4]

	category_name = CategoryList.objects.all()


	object_list = FmBlog.published.all()
	#ПАГИНАЦИЯ
	paginator = Paginator(last_postest, 3)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	#titlebanner
	banner_title = PageBanner.objects.get(pk=1)

	#Footer
	footer_content = ChangeFooter.objects.get(pk=1)

	#Flicker Gallery
	#title
	flick_name = ChangeFooterTitleGallery.objects.get(pk=1)
	
	#image
	flick_img = ChangeFooterGallery.objects.all()

	dictonary_object = {'header_phone' : header_phone,
						'category_one' : category_one, 'category_two' : category_two,
						'category_title' : category_title, 
						'post' : post,
						'banner_title' : banner_title,
						'footer_content' : footer_content,
						'flick_name' : flick_name,
						'flick_img' : flick_img,
						'category_name' : category_name,
						'last_postest' : last_postest,
						'posts' : posts, 'page' : page}

	return render(request, 'blog/post/category_direct1.html', dictonary_object)

# def category_detail(request, slug):
# 	queryset = CategoryList.objects.filter(username=slug)
# 	category = get_object_or_404(queryset, slug=slug)
# 	return render(request, 'blog/post/category_detail', {'category' : category})


def post_detail(request, year, month, day, post):
	post = get_object_or_404(FmBlog, slug=post,
									 status='published',
									 publish__year=year,
									 publish__month=month,
									 publish__day=day)

	comments = post.comments.filter(active=True)

	new_comment = None

	if request.method == 'POST':
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.post = post
			new_comment.save()
	else:
		comment_form = CommentForm()

	header_phone = ChangeHeader.objects.get(pk=1)
	category_title = ChangeTitleCategory.objects.get(pk=1)
	category_name = CategoryList.objects.all()

	recent_posts = FmBlog.objects.all()[:3]

	#titlebanner
	banner_title = PageBanner.objects.get(pk=1)

	#Footer
	footer_content = ChangeFooter.objects.get(pk=1)

	#Flicker Gallery
	#title
	flick_name = ChangeFooterTitleGallery.objects.get(pk=1)
	
	#image
	flick_img = ChangeFooterGallery.objects.all()

	dict_obj = {'post' : post,
				'header_phone' : header_phone,
				'category_title' : category_title,
				'category_name' : category_name,
				'footer_content' : footer_content,
				'flick_name' : flick_name,
				'flick_img' : flick_img,
				'banner_title' : banner_title,
				'recent_posts' : recent_posts,
				'comments' : comments, 'new_comment' : new_comment, 'comment_form' : comment_form}

	return render(request, 'blog/post/blog_single_direct.html', dict_obj)


def post_share(request, post_id):
	post = get_object_or_404(FmBlog, id=post_id, status='published')
	sent = False

	if request.method == 'Post':
		form = EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get.get_absolute_url())
			subject = f"{cd['name']} рекомендации ты читаешь" f"{post.title}"
			message = f"Читай {post.title} в {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
			send_mail(subject, message, 'admin@myblog.com', [cd['to']])
			sent = True
	else:
		form = EmailPostForm()

	#Хеадер
	header_phone = ChangeHeader.objects.get(pk=1)

	#Footer
	footer_content = ChangeFooter.objects.get(pk=1)

	#Flicker Gallery
	#title
	flick_name = ChangeFooterTitleGallery.objects.get(pk=1)
	
	#image

pagebanner/views.py
from django.shortcuts import render

# Create your views here.

bloges/templates/blog/post/block_content.html
{% load static %}

<main class="site-main">
	{% with comments.count as total_comments %}
			<!-- Blog -->
			<div class="container-fluid no-left-padding no-right-padding blog-post">
				<!-- Container -->
				<div class="container">
					<!-- Row -->
					<div class="row">
						<!-- Content Area -->
						<div class="col-md-9 col-sm-8 content-area">
							<article class="type-post">
								<div class="entry-cover">
									<img src="{{ post.fm_img.url }}" alt="Blog" />
									<div class="post-meta">
										<a href="#"><span>{{ post.publish.day }}<br>den</span>{{ post.publish.month }}<br>mnth</a>
									</div>
								</div>
								<div class="entry-content">
									<div class="entry-header">
										<h3 class="entry-title"><a href="#">{{ post.title }}</a></h3>
										<div class="entry-meta">
											<span><i class="fas fa-user"></i><a href="#">4 Comments</a></span>
											<span><i class="fa fa-clock-o"></i><a href="#">{{ post.publish }}</a></span>
											<span><i class="fas fa-comment"></i><a href="#">{{ total_comments }} Comments</a></span>
										</div>
									</div>
									<p>{{ post.body }}</p>
									{# <p>Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit. Sed ut imperdiet nisi. Proin condimentum fermentum nunc. Etiam pharetra, erat sed fermentum feugiat, velit mauris egestas quam, ut aliquam massa nisl quis neque. Suspendisse in orci enim.</p> #}
								</div>
								<div class="tags-share-block">
									<!--<div class="tags">
										<span>Tags :</span>
										<a href="#">{{ post.tags.all|join:"" }}</a>
										<a href="#" title="Auto">Auto</a>
										<a href="#" title="Cars">Cars</a>
										<a href="#" title="vehicles">vehicles</a>
									</div>-->
									<div class="share-block">
										<a href="{% url 'bloges:post_share' post.id %}" title="Share"><i class="fa fa-share"></i> Share this Post</a>
									</div>
								</div>
								<div class="about-author">
									<i><img src="{% static 'images/about-author.jpg' %}" alt="Author" /></i>
									<h3>About the author</h3>
									<p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet</p>
								</div>
							</article>
							<div id="comments" class="comments-area">
								<h2 class="comments-title">Comments</h2>
			{% for comment in comments %}
								<ol class="comment-list">
									<li class="comment byuser comment-author-admin bypostauthor even thread-even depth-1 parent">
										<div class="comment-body">
											<footer class="comment-meta">
												<div class="comment-author vcard">
													<img alt="img" src="{% static 'images/comment-1.jpg' %}" class="avatar avatar-72 photo"/>
													<b class="fn">{{ comment.name }}</b>
												</div>
												<div class="comment-metadata">
													<a href="#">{{ comment.created }}</a>											
												</div>
											</footer>
											<div class="comment-content">
												<p>{{ comment.body }}</p>
											</div>
											<div class="reply">
												<a href="#">10 Likes</a>
												<a rel="nofollow" class="comment-reply-link" href="#">Reply</a>
											</div>
										</div>
									</li>
				{% empty %}
										<div class="comment-content">
											<p>Нет комментариев, добавьте первый !</p>
										</div>
									<!--<li class="comment byuser comment-author-admin bypostauthor even thread-odd thread-alt depth-1">
										<div class="comment-body">
											<footer class="comment-meta">
												<div class="comment-author vcard">
													<img alt="img" src="assets/images/comment-2.jpg" class="avatar avatar-72 photo"/>
													<b class="fn">Mandy Janco</b>
												</div>
												<div class="comment-metadata">
													<a href="#">29 Aug 2016</a>											
												</div>
											</footer>
											<div class="comment-content">
												<p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor</p>
											</div>
											<div class="reply">
												<a href="#">25 Likes</a>
												<a rel="nofollow" class="comment-reply-link" href="#">Reply</a>
											</div>
										</div>
									</li>
									<li class="comment byuser comment-author-admin bypostauthor even thread-odd thread-alt depth-1">
										<div class="comment-body">
											<footer class="comment-meta">
												<div class="comment-author vcard">
													<img alt="img" src="assets/images/comment-3.jpg" class="avatar avatar-72 photo"/>
													<b class="fn">Canady France</b>
												</div>
												<div class="comment-metadata">
													<a href="#">05 Sep 2016</a>
												</div>
											</footer>
											<div class="comment-content">
												<p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor</p>
											</div>
											<div class="reply">
												<a href="#">15 Likes</a>
												<a rel="nofollow" class="comment-reply-link" href="#">Reply</a>
											</div>
										</div>
									</li>-->
								</ol><!-- .comment-list -->
			{% endfor %}
		{% endwith %}
								<!-- Comment Form -->
								<div id="respond" class="comment-respond">
									<h2 id="reply-title" class="comment-reply-title">Post a Comment</h2>
									<form method="post" id="commentform" class="comment-form">
					{% csrf_token %}
					{{ comment_form.as_p }}
										<!--<p class="comment-form-comment">
											<textarea id="comment" name="comment" rows="8" placeholder="Write your comment here" required="required"></textarea>
										</p>
										<p class="comment-form-author">
											<input id="author" name="author" placeholder="Your full name" size="30" maxlength="245" required="required" type="text"/>
										</p>
										<p class="comment-form-email">
											<input id="email" name="email" placeholder="Email address" required="required" type="email"/>
										</p>
										<p class="form-submit">
										</p>-->
										<input name="submit" class="submit" value="Submit" type="submit"/>
									</form>
								</div><!-- Comment Form /- -->
							</div>							
						</div><!-- Content Area /- -->

						<!-- Widget Area -->
						<div class="col-md-3 col-sm-4 widget-area">
							<!-- Widget : Search -->
							<aside class="widget widget_search">
								<form method="get" class="searchform" action="#">
									<div class="input-group">
										<input placeholder="Search Here" class="form-control" required="" type="text"/>
										<span class="input-group-btn">
											<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
										</span>
									</div>
								</form>
							</aside><!-- Widget: Search /- -->
							<!-- Widget : Categories -->
							<aside id="categories" class="widget widget_categories">
								<h3 class="widget-title">{{ category_title.category_title }}</h3>
								<ul>
					{% for obj_category in category_name %}
										<li><a href="{% url 'bloges:category_list' obj_category.slug %}">{{ obj_category.category_name }}</a></li>
					{% endfor %}
									<!--<li><a href="#">Egg Fryed Rice With Vegitable</a></li>
									<li><a href="#">Grill Chickentry Foodmanjuri</a></li>
									<li><a href="#">Fishfry Apilimied Dish</a></li>
									<li><a href="#">Intepsion California Epsia</a></li>
									<li><a href="#">Soadynegth Ofriaplat Disha</a></li>-->
								</ul>
							</aside><!-- Widget: Categories /- -->
							<!-- Widget : Recent Post -->
							<aside class="widget widget_recentposts">
								<h3 class="widget-title">Recent POSTS</h3>
					{% for recent_post in recent_posts %}
								<div class="latest-content">
									<a href="{{ recent_post.get_absolute_url }}" title="Recent Posts"><i><img src="{{ recent_post.fm_img.url }}" class="wp-post-image main-img" alt="blog-1"></i></a><br>
									<h5 class="recent-title"><a title="Pellentesque suscipit ante at" href="{{ recent_post.get_absolute_url }}">{{ recent_post.title }}</a></h5>
									<span><a href="{{ recent_post.get_absolute_url }}">{{ recent_post.publish }}</a></span>
								</div>
					{% endfor %}
								<!--<div class="latest-content">
									<a href="#" title="Recent Posts"><i><img src="assets/images/rcnt-2.png" class="wp-post-image" alt="blog-1"></i></a>
									<h5><a class="tc_dark tc_green_h" title="Pellentesque suscipit ante at" href="#">Special restaurant with nonveg porn</a></h5>
									<span><a href="#">June 09, 2016</a></span>
								</div>
								<div class="latest-content">
									<a href="#" title="Recent Posts"><i><img src="assets/images/rcnt-3.png" class="wp-post-image" alt="blog-1"></i></a>
									<h5><a title="Pellentesque suscipit ante at" href="#">fishfried Chicken Qualit anjascan food</a></h5>
									<span><a href="#">April  22, 2016</a></span>
								</div>
							</aside>--><!-- Widget : Recent Post -->
							<!-- Widget : Tags -->
							<!--<aside class="widget widget_latesttweets">
								<h3 class="widget-title">Tags: </h3>
								<div class="tagcloud">
									<a href="#" title="Food">food</a>
									<a href="#" title="Break fast & LUNCH">break fast & LUNCH</a>
									<a href="#" title="Drinks">Drinks</a>
									<a href="#" title="DINNER & EVENTS">DINNER & EVENTS</a>
									<a href="#" title="Serve">serve</a>
									<a href="#" title="Chef">chef</a>
									<a href="#" title="Blog">Blog</a>
								</div>
							</aside>--><!-- Widget : Tags /- -->
						</div><!-- Widget Area /- -->
					</div><!-- Row /- -->
				</div><!-- Container /- -->
			</div><!-- Blog -->
			
		</main>

bloges/templates/blog/post/blog_single_direct.html
{% extends 'blog/post/blog-single.html' %}
{% load static %}

{% block singlepost %}
	{% include "blog/post/page_banner.html" %}

	{% include "blog/post/block_content.html" %}
{% endblock %}

bloges/templates/blog/post/page_banner.html
{% load static %}
<!-- Page Banner -->
	<div class="container-fluid no-left-padding no-right-padding page-banner error-banner">
		<!-- Container -->
		<div class="container">
			<div class="page-title">
				<h3>{{ banner_title.banner_name }}</h3>
			</div>
			<ol class="breadcrumb">
				<li><a href="{% url 'bloges:index' %}">{{ banner_title.banner_btn_1 }}</a></li>
				<li><a href="{% url 'bloges:post_list' %}">{{ banner_title.banner_btn_2 }}</a></li>
				<li class="active">{{ post.title }}</li>
			</ol>
		</div><!-- Container /- -->
	</div><!-- Page Banner /- -->